### PR TITLE
Improve test coverage of BrendelBethge attack

### PR DESCRIPTION
**Pull request by zimmerrol**
This PR increases the test coverage of the `BrendelBethge` attack and fixes a bug in the initialization of the adversarial examples inside the attack.

### CODE REVIEW

**Comment by jonasrauber** [comment]
@zimmerrol ping

**Comment by zimmerrol** [comment]
@jonasrauber There is still the problem that the attack fails for the `jax` models and only for these. Do you think this might suggest an inconsistent behavior of the `eagerpy` across the different frameworks?

**Comment by jonasrauber** [comment]
Are you sure this only fails for JAX?
The error message looks like it should probably fail for all frameworks (JAX is just the fastest one to reach that point)… i.e. looks like the attack is broken for targeted attacks?!
/cc @wielandbrendel

**Comment by zimmerrol** [comment]
I've just rerun the test with the pytorch backend locally and there the targeted attacks pass. That's what made me think that it's only a JAX problem.

**Comment by jonasrauber** [comment]
`skipslow` is missing

**Comment by divyam3897** [comment]
I was testing this attack with PyTorch (after the minor fixes) but it failed for me too. I am not sure if it's related to this issue but this was the error I got:
` 
 File "evaluate_meta_cifar.py", line 391, in main
    adversarial, _, success = attack(fmodel, X, y, epsilons=epsilons)
  File "foolbox/attacks/base.py", line 410, in __call__
    xp = self.run(model, x, criterion, early_stop=early_stop, **kwargs)
  File "foolbox/attacks/brendel_bethge.py", line 435, in run
    assert is_adversarial(best_advs).all()
AssertionError
`
I tried with both Linfty and L2 attack on a Linfty trained model but since the error was in the base class, both of them failed.

**Pull request closed without merging**
