### PR TITLE
Added Decoupled Direction and Norm attack

### PR DESCRIPTION
**Pull request by jeromerony**
Added the Decoupled Direction and Norm L2 adversarial attack from https://arxiv.org/abs/1811.09600.

### CODE REVIEW

**Comment by jeromerony** [comment]
There is a [step](https://github.com/jeromerony/foolbox/blob/0e0c415360715018385820f5b1d1fd5025b31698/foolbox/attacks/decoupled_direction_norm.py#L85) in the algorithm where I check if the gradient norm is zero to avoid dividing by zero however this is not covered by the tests. I added that because it happened a few times on a MNIST classifier that the gradient in float32 precision would be zero. Any idea as if it should removed or included in the tests? @jonasrauber

**Comment by jonasrauber** [comment]
Hi @jeromerony! That's excellent work. Thanks for your contribution. Regarding your question: I think it's fine to not cover that if clause in the tests, just add ```# pragma: no cover```.

**Comment by jonasrauber** [comment]
Decided to do it myself. And added it to the docs as well. Once the tests have run through, I think we can merge this.

**Comment by jeromerony** [comment]
Thanks a lot!

**Pull request merged**
