### PR TITLE
Add Adam based PGD attacks

### PR DESCRIPTION
**Pull request by FlashTek**
This PR adds variants of the PGD attack that use an Adam optimizer to find the adversarial example instead of using vanilla gradient descent. This attack is described in a paper by [Carlini & Wagner](https://arxiv.org/pdf/1608.04644.pdf); @wielandbrendel suggested to add these attacks to `foolbox`, too.

@jonasrauber I tried to perform only the minimal amount of modifications to the existing code/classes to add the Adam optimizer. Nevertheless, I am not sure if I have actually chosen the most elegant/efficient way. Looking forward to hearing your thoughts about it!

### CODE REVIEW

**Comment by FlashTek** [comment]
@jonasrauber The coverage decreased for the `BoundaryAttack` which I haven't touched at all. It looks like some lines that are supposed to catch rare errors were not hit in this test run: I think we should optimize the tests for this attack so that the test-coverage is more deterministic in a future PR.

**Comment by jonasrauber** [comment]
Certainly nice work!

Regarding the code style: From glancing over it, it follows the spirit of the other attacks in the `iterative_projected_gradient` module. In the future we might want to rethink our current approach of implementing all these attacks, but for now that's fine.

Regarding the attack implementation: have you tried on a real network and does everything perform "as expected" e.g. compared to standard PGD?

**Comment by jonasrauber** [comment]
Oh, and like always: please add it to the docs.

**Comment by FlashTek** [comment]
Thanks! I've added the new attacks to the documentation as requested.

Yes, I have also tested it on a real network and the efficiency of the adam-based attack is better than the standard PGD - just as expected.

**Pull request merged**
