### PR TITLE
Fixing numercal instabilities #565

### PR DESCRIPTION
**Pull request by wielandbrendel**
This PR addresses #565

### CODE REVIEW

**Comment by wielandbrendel** [comment]
@jonasrauber The errors are not really related to this PR, right?

**Comment by jonasrauber** [comment]
> @jonasrauber The errors are not really related to this PR, right?

Right, seems like it might have been caused by a network problem on GitHub's CI. I restarted the tests, maybe we were just unlucky.

**Comment by jonasrauber** [comment]
Nevermind, misread the error message. It's some TensorFlow problem. Has nothing to do with this PR. I will look into it.

**Comment by jonasrauber** [comment]
Updated master (TensorFlow version) to make sure master tests still pass (they do, now). Updated this PR accordingly.

**Comment by jonasrauber** [comment]
@wielandbrendel Can be merged now. Should I, or did you want to make more changes to this?

**Comment by wielandbrendel** [comment]
@jonasrauber Great, thanks so much!

**Pull request merged**
