### PR TITLE
change name, stepsize, default search, add author

### PR DESCRIPTION
**Pull request by Jianbo-Lab**
@jonasrauber Please merge the changes on the previous Boundary Attack++, resulting from changes and improvements in the preprint. The changes in the code are

1. Following suggestions from my collaborators, we decided to change the name of Boundary Attack++ to HopSkipJumpAttack.
2. A new author, Martin J. Wainwright, is added to the paper.
3. Update the choice of stepsize based on a newly established theorem.
4. Change default stepsize search to "geometric progression".

### CODE REVIEW

**Comment by Jianbo-Lab** [comment]
It looks like the checks failed at conftest.py, a file I didn't touch. I am a bit confused about what led to the failure.

**Comment by FlashTek** [comment]
@Jianbo-Lab I think the issue that made the build fail have been resolved by @jonasrauber lately in [this commit](https://github.com/bethgelab/foolbox/commit/4ffc9fc762222e4e354d7cfe0b2cb226c4082a82). Therefore, your PR should pass verification once you merge the master branch into your branch or rebase.

**Comment by Jianbo-Lab** [comment]
Thanks @FlashTek ! It seems the new commit does not help fix my issue after I merge. I will later create a new pull request to double check.

**Comment by FlashTek** [comment]
@Jianbo-Lab I think there is no need to create a new PR to check. It looks like there is now a different problem that makes the tests fail. I noticed that you also need another [commit ](https://github.com/bethgelab/foolbox/pull/343/commits/a347fa7973053d77276f2c7190550c84dc5151f1) to fix the problem. Maybe you can just add the additional `ignore::FutureWarning` line to the `setup.cfg` and check if it solves the issue - it did for me. Also, I noticed that you need to fix som pep8 related issues in your code (according to flake):

```
./foolbox/attacks/hop_skip_jump_attack.py:535:1: E302 expected 2 blank lines, found 1
./foolbox/attacks/hop_skip_jump_attack.py:535:70: W291 trailing whitespace
./foolbox/attacks/hop_skip_jump_attack.py:536:5: E128 continuation line under-indented for visual indent
./foolbox/attacks/hop_skip_jump_attack.py:536:5: E125 continuation line with same indent as next logical line
./foolbox/attacks/hop_skip_jump_attack.py:553:1: W391 blank line at end of file
./foolbox/tests/attacks/test_attacks_hsja.py:103:1: E302 expected 2 blank lines, found 1
./foolbox/tests/attacks/test_attacks_hsja.py:108:39: W292 no newline at end of file
```

**Comment by Jianbo-Lab** [comment]
Cool! The checks passed after I fixed the issues you pointed out. Great thanks @FlashTek ! 

It seems now I met the same problem as one of your pull requests: coverage decreased because of other scripts I didn't touch. I will wait for @jonasrauber to fix the issue.

**Comment by jonasrauber** [comment]
@Jianbo-Lab Sorry for not getting back earlier! Looking forward to merge this. Could you also change the name in the docs, then we should be good to go.

**Pull request merged**
