### PR TITLE
Implementation of GenAttack

### PR DESCRIPTION
**Pull request by zimmerrol**
Implementation of the attack described in [GenAttack: Practical Black-box Attacks with Gradient-Free Optimization](https://arxiv.org/pdf/1805.11090.pdf).

### CODE REVIEW

**Comment by jonasrauber** [comment]
Please add it to the docs

**Comment by jonasrauber** [comment]
So far looks good, but want to go through the code a bit more carefully.

**Comment by jonasrauber** [comment]
@zimmerrol Is this PR ready to be merged?

**Comment by zimmerrol** [comment]
@jonasrauber Yes, it is.

**Pull request merged**
