### PR TITLE
add astype dtype in slsqp

### PR DESCRIPTION
**Pull request by gwding**
1. convert dtype to resolve data type doesn't match error
2. fixed slicing in localsearch

### CODE REVIEW

**Comment by jonasrauber** [comment]
@gwding Thanks for your pull-request. I get the dtype fixes, but what is the added `slice` supposed to do / solve?

**Comment by gwding** [comment]
@jonasrauber my understanding is that `perturbed[location]` is trying to get the pixel. If it is RGB image, then `perturbed[location].shape` should be `(3, )`. and it seems that `slice(None)` is the way to slice it. If you use `None`, it is adding a new dimension.

To give a short example,
```
import numpy as np
print(np.ones((3, 32, 32))[(slice(None), 3, 3)].shape)
print(np.ones((3, 32, 32))[(None, slice(None), 3, 3)].shape)
print(np.ones((3, 32, 32))[(None, 3, 3)].shape)
```
I believe the first one is what we want to do.

**Comment by jonasrauber** [comment]
Oh, of course 🙈
If the channel axis is the last one, it doesn't matter (which is why I didn't have problems).

**Comment by jonasrauber** [comment]
Thanks a lot @gwding

**Pull request merged**
