### PR TITLE
Implementation of more Batch attacks

### PR DESCRIPTION
**Pull request by FlashTek**
The aim if this PR is to port all existing attacks to the new auto-batching mode. In this initial version of the PR only a subset of the attacks will be ported as some attacks rely on 3rd-party python libraries which make the porting harder (`slsqp` and `lbfgs`). In the end, these attacks should also be included in this PR or follow-up PR.

Content:

- Ported the existing attacks to the new auto-batching interface
- Added support for `forward()` and `forward_and_gradient_one()` calls in `YieldingAdversarial`, `batching.py` and all models

Known problems:

- The `Sparsefool` and `Localsearch` attacks fail to find adversarial examples, i.e. their unit tests fail. I cannot see the reason why this happens and would appreciate the help of @jonasrauber: maybe you can take a look at the two modules to check what goes wrong.

-  The auto-batching mechanism fuses calls of `forward_one` and `gradient_one` of multiple attacks into one call of the batched version (i.e. `forward` respectively `backward`). Some attacks already use the batched version (`forward`) to test multiple proposals for adversarial examples at the same right. It's unclear to me how to treat these attacks: should we just merge incoming `forward` calls by the attacks into "super-batches"? Should we rewrite the attacks so that the batched versions are not used anymore?
As for now, I have decided to go with the first option, but I feel like this is not the optimal way.

### CODE REVIEW

**Comment by jonasrauber** [comment]
Thanks @FlashTek. We indeed have two options to handle attacks that already use batches (e.g. Boundary Attack; what else?) and both have their advantages and disadvantages. For now, I think it’s best to do what you already started with, i.e. also auto-batching the batched forward calls (together with forward_one calls) and not changing the attacks. At some later point it could be interesting to add an alternative version of such an attack that only uses the auto-batching to see how they compare (probably depends on the attack and the concrete problem).

I will have a look at the SparseFool and LocalSearch problems.

**Comment by FlashTek** [comment]
You're right, at the moment there are only three attacks using batches: `BoundaryAttack` , `BoundaryAttack++` and `LocalSearch`.

**Comment by jonasrauber** [comment]
@FlashTek Can you remind me about the state of this PR. Are we currently just waiting because of the problems with `SparseFool` and `LocalSearch`. In that case, maybe let's move them to a different PR if that's not too much work.

**Comment by FlashTek** [comment]
@jonasrauber I had to remove the binarization attack as the current way of calling the batched attacks does not allow to create one `YieldingAdversarial`, pass it through one attack and then pass it through another attack. This was required to efficiently test the `BinarizationAttack`; I think that we should extend the functions defined in `batching.py` so that either a numpy array of images or a list of `YieldingAdversarial` objects can be passed to it. If you agree with me here I will work on this in another PR and add the batched binarization attack then again.

**Comment by jonasrauber** [comment]
@FlashTek Could you open an issue showing what goes wrong. I have a rough idea but I am not following completely right now.

**Comment by FlashTek** [comment]
@jonasrauber The problem I saw was the following: the BinarizationAttack is applying a refinement, i.e. can only improve already found adversarial examples. Therefore, we do not only have to pass the original image but also the already found (found by another attack) adversarial example to the attack. In the non-batched version, this could either be done by passing an `Adversarial` object or by using the `starting_point` parameter. The former is not possible anymore with the new batching API, and the latter is not really usable as currently, we can only pass the same parameter to all attacks in a batch.

After I thought about the issue a little bit longer, I don't think we need to open a new issue: I think we can solve my initial worries by solving [issue 349 ](https://github.com/bethgelab/foolbox/issues/349).  as this already gives us a way how to specify the `starting_point` parameter for each attack call individually.  

All in all, I don't think that this issue blocks merging this PR anymore, as I have removed the affected attack (`BinarizationAttack`) from it. If you agree with me, I will open a new PR introducing a batched version of this attack again once issue 349 is solved.

**Pull request merged**
