### PR TITLE
Add SparseFool attack

### PR DESCRIPTION
**Pull request by amodas**
Hello,

I implemented the code of our recent sparse attack namely SparseFool (CVPR 2019). More details about the method can be found here: [https://arxiv.org/abs/1811.02248](https://arxiv.org/abs/1811.02248).

Looking forward to your feedback!

### CODE REVIEW

**Comment by jonasrauber** [comment]
Thanks @amodas! That's great work! Looking forward to merging this once all tests pass. Let me know if I can be of any help.

**Comment by jonasrauber** [comment]
Please also add an entry in the docs (list of attacks and list of gradient-based attacks). I can also do it later...

**Comment by wielandbrendel** [comment]
@amodas Great work, thanks for the PR!

I have a quick question: your attack optimises L1, right? Just asking because in the paper you compare to L0 attacks (JSMA, 1-PA), right? Did you also compare to the Elastic Net attack (which actually optimises L1)? In table 1, is the perturbation measured in L0 or L1?

**Comment by amodas** [comment]
@jonasrauber 
Thanks! I will update the docs once all tests pass!

@wielandbrendel
We actually "approximate" L0 through the L1. Since we know that for linearly constrained problems the L0 solution can be very well approximated by the L1 (some times it's also optimal), we are looking for a way to linearize (and simplify) our problem. We achieve such a relaxation by approximating the decision boundary as an affine hyperplane, and the L1 solution is computed.

Thus, since we "approximate" the L0 solution, we only compare with L0 attacks, and the Elastic Net is not evaluated.

In table 1we measure the L0 of the perturbation, but in terms of pixels (distorting whichever of the RGB components of a pixel, will count as a single perturbed pixel).

**Comment by amodas** [comment]
> Thanks @amodas! That's great work! Looking forward to merging this once all tests pass. Let me know if I can be of any help.

@jonasrauber 
I could really use some insights about why the coverage decreases...

Could it be related to this?: 
Inside the boundary_approximation_deepfool, which is a slightly modified version of DeepFool, I want to ignore the fact that the image values might be out of bounds.

That is, we want an unconstrained DeepFool, since we just want to reach the decision boundary. For that reason, for the computation of the predictions and the gradients, I set strict=False.

**Comment by jonasrauber** [comment]
You can click on the details link to see why ;-)
Ignore the keras model decrease, that was caused by me and is fixed.
The main thing missing in this PR is a test in `foolbox/tests/` that actually runs this attack on a test model. You could just have a look at the test for a similar attack and adapt it accordingly. The tests are a bit messy right now.

**Comment by amodas** [comment]
Thanks for the feedback and sorry for the inconvenience; I'm not very familiar with all of the process and the frameworks :(

I will create at test for SparseFool and I will try again the coverage!

Thanks!

**Comment by amodas** [comment]
Hello,

I created the test_attacks_sparsefool, and eventually sparsefool achieves 100% of coverage.
However, again, the coverage seems to have been decreased...

It seems that the `__exit__` method of the class `Model` (base.py) is never called, and then there are uncovered parts in the `CaffeModel` (caffe.py).

I would really appreciate any help or suggestions! :)

Thanks!

**Comment by jonasrauber** [comment]
No worries, coveralls sometimes misrepresents its own results. Great job, thanks!

**Comment by amodas** [comment]
@jonasrauber 
That's great! Thanks for the support :)

**Comment by jonasrauber** [comment]
@amodas Could you make another small PR to add it to the docs? I forgot about that before merging.

**Comment by machengcheng2016** [comment]
How to utilize the SparseFoolAttack, please? 
image

**Pull request merged**
